version: '3.5'

services:
  jupyter:
    image: jupyter/tensorflow-notebook:2ce7c06a61a1
    container_name: jupyter
    env_file:
      - ./.python.env
    ports:
      - '8888:8888'
      - '80:8501'
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./dashboard:/home/jovyan/dashboard
      - ./organized\ notebooks:/home/jovyan/organized\ notebooks

networks:
  default:
    name: ds4a_team84
